name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  install-dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Use Node.js 23
        uses: actions/setup-node@v4
        with:
          node-version: 23.6.1
          cache: "yarn"

      - name: Install Dependencies
        run: yarn install --frozen-lockfile
